- name: Installing mysql
  hosts: mysql
  become: yes
  tasks:
  - name: lets disable MySQL 8 version.
    command: yum module disable mysql -y 

  - name: Setup the MySQL5.7 repo file
    copy: 
      src: mysql.repo
      dest: /etc/yum.repos.d/mysql.repo

  - name: Install MySQL Server
    yum:
      name: mysql-community-server
      state: installed

  - name: Start MySQL Service
    service: 
      name: mysqld
      state: started
      enabled: yes

  - name: change the default root password in order to start using the database service.
    command: mysql_secure_installation --set-root-pass RoboShop@1

  - name:  check the new password working or not.
    command: mysql -uroot -pRoboShop@1
