- name: Configuring the payment application
  hosts: payment
  become: true
  tasks:
  - name: Install python 3.6
    yum:
      name: "{{item}}"
      state: installed
    loop:
    - python36 
    - gcc 
    - python3-devel