- name: Configuring Web app
  hosts: web
  become: yes
  tasks:
  - name: Install nginx
    yum: 
      name: nginx
      state: installed
  
  - name: Start & Enable Nginx service
    service: 
      name: nginx
      state: started
      enabled: yes

  - name: Remove the default content that web server is serving.
    file:
      path: /usr/share/nginx/html/*
      state: absent

  - name: Download the frontend content
    get_url: 
      url: https://roboshop-builds.s3.amazonaws.com/web.zip
      dest: /tmp
    
  - name: Extract the frontend content.
    unarchive:
      path: /tmp/web.zip
      dest: /usr/share/nginx/html

  - name: Create Nginx Reverse Proxy Configuration.
    copy: 
      src: roboshop.conf 
      dest: /etc/nginx/default.d/roboshop.conf

  - name: Restart Nginx Service to load the changes of the configuration.
    service:
      name: nginx
      state: restarted